miningtaxes/urls.py
from django.urls import path

from . import views

app_name = "miningtaxes"

urlpatterns = [
    path("", views.index, name="index"),
    path("launcher", views.launcher, name="launcher"),
    path("add_character", views.add_character, name="add_character"),
    path("add_admin_character", views.add_admin_character, name="add_admin_character"),
    path(
        "remove_character/<int:character_pk>/",
        views.remove_character,
        name="remove_character",
    ),
    path(
        "remove_admin_registered/<int:character_pk>/",
        views.remove_admin_registered,
        name="remove_admin_registered",
    ),
    path(
        "remove_admin_character/<int:character_pk>/",
        views.remove_admin_character,
        name="remove_admin_character",
    ),
    path(
        "character_viewer/<int:character_pk>/",
        views.character_viewer,
        name="character_viewer",
    ),
    path(
        "curmonthgraph",
        views.curmonthgraph,
        name="curmonthgraph",
    ),
    path(
        "purge_old_corphistory",
        views.purge_old_corphistory,
        name="purge_old_corphistory",
    ),
    path(
        "char_mining_ledger_data/<int:character_pk>/",
        views.char_mining_ledger_data,
        name="character_mining_ledger_data",
    ),
    path(
        "user_mining_ledger_90day/<int:user_pk>",
        views.user_mining_ledger_90day,
        name="user_mining_ledger_90day",
    ),
    path("user_summary/<int:user_pk>", views.user_summary, name="user_summary"),
    path(
        "summary_month_json/<int:user_pk>",
        views.summary_month_json,
        name="summary_month_json",
    ),
    path(
        "admin_get_all_activity_json",
        views.admin_get_all_activity_json,
        name="admin_get_all_activity_json",
    ),
    path(
        "all_tax_credits/<int:user_pk>",
        views.all_tax_credits,
        name="all_tax_credits",
    ),
    path("faq", views.faq, name="faq"),
    path("ore_prices", views.ore_prices, name="ore_prices"),
    path("ore_prices_json", views.ore_prices_json, name="ore_prices_json"),
    path("leaderboards", views.leaderboards, name="leaderboards"),
    path("admin/", views.admin_launcher, name="admin_launcher"),
    path("admin/tables", views.admin_tables, name="admin_tables"),
    path("admin_main_json", views.admin_main_json, name="admin_main_json"),
    path("admin_char_json", views.admin_char_json, name="admin_char_json"),
    path(
        "admin_mining_by_sys_json",
        views.admin_mining_by_sys_json,
        name="admin_mining_by_sys_json",
    ),
    path(
        "admin_tax_revenue_json",
        views.admin_tax_revenue_json,
        name="admin_tax_revenue_json",
    ),
    path("admin_month_json", views.admin_month_json, name="admin_month_json"),
    path(
        "admin_corp_mining_history",
        views.admin_corp_mining_history,
        name="admin_corp_mining_history",
    ),
    path("admin_corp_ledger", views.admin_corp_ledger, name="admin_corp_ledger"),
]

miningtaxes/models/orePrices.py
# Shamelessly stolen from Member Audit
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from eveuniverse.models import EveType, EveTypeMaterial

from allianceauth.services.hooks import get_extension_logger
from app_utils.logging import LoggerAddTag

from .. import __title__
from ..app_settings import (
    MININGTAXES_ALWAYS_TAX_REFINED,
    MININGTAXES_REFINED_RATE,
    MININGTAXES_UNKNOWN_TAX_RATE,
)
from ..helpers import PriceGroups
from .settings import Settings

logger = LoggerAddTag(get_extension_logger(__name__), __title__)


def get_tax(eve_type):
    settings = Settings.load()
    pg = PriceGroups()
    if eve_type.eve_group_id not in pg.taxgroups:
        logger.debug(
            "Unknown evetype for %s, group: %d" % (eve_type, eve_type.eve_group_id)
        )
        return MININGTAXES_UNKNOWN_TAX_RATE
    group = "tax_" + pg.taxgroups[eve_type.eve_group_id]
    return settings.__dict__[group] / 100.0


def ore_calc_prices(eve_type, q):
    try:
        ore = OrePrices.objects.get(eve_type=eve_type)
        return q * ore.raw_price, q * ore.refined_price, q * ore.taxed_price
    except OrePrices.DoesNotExist:
        pass
    quantity = q
    raw_price = quantity * get_price(eve_type)
    materials = EveTypeMaterial.objects.filter(
        eve_type_id=eve_type.id
    ).prefetch_related("eve_type")
    refined_price = 0.0
    for mat in materials:
        q = MININGTAXES_REFINED_RATE * (mat.quantity * quantity) / eve_type.portion_size
        refined_price += q * get_price(mat.material_eve_type)
    if refined_price == 0.0:
        refined_price = raw_price
    taxed_value = refined_price
    if raw_price > taxed_value:
        taxed_value = raw_price
    return raw_price, refined_price, taxed_value


def get_price(eve_type):
    ore = None
    try:
        ore = OrePrices.objects.get(eve_type=eve_type)
    except ObjectDoesNotExist:
        pass
    if ore is None:
        mp = None
        try:
            mp = eve_type.market_price
        except EveType.market_price.RelatedObjectDoesNotExist:
            pass
        if mp is None:
            return 0.0
        if eve_type.market_price.average_price is not None:
            return eve_type.market_price.average_price
        if eve_type.market_price.adjusted_price is not None:
            return eve_type.market_price.adjusted_price
        return 0.0
    return ore.buy


class OrePrices(models.Model):
    eve_type = models.OneToOneField(
        EveType,
        on_delete=models.deletion.CASCADE,
        unique=True,
    )
    buy = models.FloatField()
    sell = models.FloatField()
    raw_price = models.FloatField(default=0.0)
    refined_price = models.FloatField(default=0.0)
    taxed_price = models.FloatField(default=0.0)
    updated = models.DateTimeField()

    def calc_prices(self):
        self.raw_price = self.buy
        materials = EveTypeMaterial.objects.filter(
            eve_type_id=self.eve_type.id
        ).prefetch_related("eve_type")
        self.refined_price = 0.0
        for mat in materials:
            q = MININGTAXES_REFINED_RATE * mat.quantity / self.eve_type.portion_size
            self.refined_price += q * get_price(mat.material_eve_type)
        if self.refined_price == 0.0:
            self.refined_price = self.raw_price
        self.taxed_price = self.refined_price
        if not MININGTAXES_ALWAYS_TAX_REFINED and self.raw_price > self.taxed_price:
            self.taxed_price = self.raw_price
        self.save()

miningtaxes/templates/miningtaxes/admin_launcher.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}
{% load bootstrap %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
		<h3 class="panel-title">{% translate 'MiningTaxes Settings' %} (v{{ version }})</h3>
        </div>
        <div class="panel-body">
	    <form class="form" action="{{ url }}" method="POST">
		    {% csrf_token %}
		    {{ form|bootstrap }}
		    <button type="submit" class="btn btn-primary">Edit Settings</button>
	    </form>
	</div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Accountant Characters (add only one accountant per corp)' %}</h3>
        </div>
        <div class="panel-body">
            <!-- Characters -->
            <div class="character-cards">
                <ul class="cards_container">
                    <!-- Add New Character -->
                    <li class="cards_item">
                        <div class="card">
                            <div class="card-header">{% translate 'Register Character' %}</div>

                            <div class="card-body card__content">
                                <a href="{% url 'miningtaxes:add_admin_character' %}">
                                    <img src="{{ 1|character_portrait_url:256 }}" alt="Add character">
                                </a>
                            </div>

                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm" href="{% url 'miningtaxes:add_admin_character' %}">{% translate 'Register' %}</a>
                            </div>
                        </div>
                    </li>

                    {% if has_registered_characters %}
                        <!-- Registered Characters -->
                        {% for auth_character in auth_characters|dictsort:"character_name" %}
                            <li class="cards_item">
                                <div class="card">
                                    <div class="card-header">
                                        {{ auth_character.character_name }}
                                    </div>
                                    <div class="card-body card__content">
                                        <p>
					<a href="">
                                                <span class="aa-miningtaxes-launcher-character-image">
                                                    <img src="{{ auth_character.character_id|character_portrait_url:256 }}" alt="{{ auth_character.character_name }}">

                                                    {% if auth_character.alliance_id %}
                                                        <span class="aa-miningtaxes-alliance-logo">
                                                            <img class="" src="{{ auth_character.alliance_id|alliance_logo_url:64 }}" title="{{ auth_character.alliance_name }}">
                                                        </span>
                                                    {% endif %}

                                                    <span class="aa-miningtaxes-corporation-logo">
                                                        <img class="" src="{{ auth_character.corporation_id|corporation_logo_url:64 }}" title="{{ auth_character.corporation_name }}">
                                                    </span>
                                                </span>
                                            </a>
                                        </p>

                                        <div class="text-center">
                                        </div>
                                    </div>

                                    <div class="card-footer">
                                        <a class="btn btn-danger btn-sm" href="{% url 'miningtaxes:remove_admin_character' auth_character.character.pk %}"
                                            role="button" title="{% translate 'Remove this character.' %}"
                                            onclick="return confirm('Are you sure you want to REMOVE this character?')">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Registered Characters in plugin' %}</h3>
        </div>
        <div class="panel-body">
            <!-- Characters -->
            <div class="character-cards">
                        <!-- Registered Characters -->
                        {% for auth_character in auth_registered|dictsort:"character_name" %}
                                        <a class="btn btn-danger btn-sm" href="{% url 'miningtaxes:remove_admin_registered' auth_character.character.pk %}"
                                            role="button" title="{% translate 'Remove this character.' %}"
							  onclick="return confirm('Are you sure you want to REMOVE {{auth_character.character_name}}? All mining history and tax history will be erased!')">
						<i class="far fa-trash-alt"></i> {{auth_character.character_name}}
                                        </a>
                        {% endfor %}
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Admin actions' %}</h3>
        </div>
        <div class="panel-body">
		<ul>
			<li>
				<a class="btn btn-danger btn-sm" href="{% url 'miningtaxes:purge_old_corphistory' %}"
				    role="button" title="{% translate 'Purge corp mining history older than 90 days.' %}"
				    onclick="return confirm('Are you sure you want to PURGE corp mining history older than 90 days?')">
				    <i class="far fa-trash-alt"></i> Purge corp history older than 90 days
				</a>
			</li>
		</ul>
        </div>
    </div>


{% endblock details %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'miningtaxes/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/miningtaxes.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

miningtaxes/templates/miningtaxes/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% load navactive %}

{% block page_title %}{% translate "miningtaxes" %}{% endblock %}

{% block content %}
    <div class="miningtaxes">
	 <br/>

	<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'miningtaxes:index' %}">Mining Taxes</a>
	</div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
	        <li class="{% navactive request 'miningtaxes:ore_prices' %}">
                    <a href="{% url 'miningtaxes:ore_prices' %}">
                        {% translate 'Current Ore Prices' %}
                    </a>
                </li>
	        <li class="{% navactive request 'miningtaxes:faq' %}">
                    <a href="{% url 'miningtaxes:faq' %}">
                        {% translate 'FAQ' %}
                    </a>
                </li>
	        <li class="{% navactive request 'miningtaxes:launcher' %}">
                    <a href="{% url 'miningtaxes:launcher' %}">
                        {% translate 'Setup' %}
                    </a>
                </li>

		{% if perms.miningtaxes.auditor_access %}
		<li class="{% navactive request 'miningtaxes:admin_tables' %}">
                        <a href="{% url 'miningtaxes:admin_tables' %}">
                            {% translate 'Audit Reports' %}
                        </a>
                </li>
                {% endif %}
		{% if perms.miningtaxes.admin_access %}
		<li class="{% navactive request 'miningtaxes:admin_launcher' %}">
                        <a href="{% url 'miningtaxes:admin_launcher' %}">
                            {% translate 'Admin Setup' %}
                        </a>
                </li>
                {% endif %}

	    </ul>
        </div>
        </div>
	</nav>
        {% block details %}{% endblock %}
    </div>
{% endblock %}

miningtaxes/templates/miningtaxes/character_viewer.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
		<h3 class="panel-title">Mining Ledger for {{ character.name }}</h3>
        </div>
        <div class="panel-body">

    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="tab_mining_ledger">
            <thead>
                <tr>
                    <th>{% translate 'Date' %}</th>
                    <th>{% translate 'Type' %}</th>
                    <th>{% translate 'Quantity' %}</th>
                    <th>{% translate 'Raw' %}</th>
                    <th>{% translate 'Refined' %}</th>
                    <th>{% translate 'Taxed' %}</th>
                    <th>{% translate 'Owed' %}</th>
                    <th>{% translate 'Solar System' %}</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
	</div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'miningtaxes/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/miningtaxes.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
$(document).ready(function () {
        $('#tab_mining_ledger').DataTable({
            ajax: {
                url: "{% url 'miningtaxes:character_mining_ledger_data' character.pk %}",
                dataSrc: 'data',
                cache: false
            },
            columns: [
                { data: 'date' },
                { data: 'type' },
                {
                    data: 'quantity',
                    render: $.fn.dataTable.render.number(',', '.', 0)
                },
                {
                    data: 'raw price',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                {
                    data: 'refined price',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                {
                    data: 'taxed value',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                {
                    data: 'taxes owed',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                { data: 'solar_system' },
            ],
            order: [[0, "desc"], [1, "asc"] , [4, "asc"]],
        });
});
{% endblock %}

miningtaxes/templates/miningtaxes/faq.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
		<h3 class="panel-title">Frequently asked questions</h3>
        </div>
        <div class="panel-body">
		<h4>How do I pay my taxes?</h4>
		<ol>
			<li>Search for any of the following corps: <b> {{ corps }} </b></li>
			<li>Click on the three dots on the upper right on the information screen about the corp: <br/>
				<div class='imgcontainer'> <img src="{% static 'miningtaxes/images/faq1.png' %}"/> </div>
			</li>
			<li>Select 'Give Money': <br/>
				<div class='imgcontainer'> <img src="{% static 'miningtaxes/images/faq2.png' %}"/> </div>
			</li>
			<li>Enter the appropriate amount and the phrase '{{ phrase }}' (case insensitive) without the quotes for the reason: <br/>
				<div class='imgcontainer'>
				<img src="{% static 'miningtaxes/images/faq3.png' %}"/>
				<div class='text'> {{ phrase }} </div>
				</div>
			</li>
		</ol>

    </div>
	</div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'miningtaxes/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/miningtaxes.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/launcher.css' %}" type="text/css">
<style>
.imgcontainer {
  position: relative;
  left: 100px;
  text-align: left;
  color: white;
}
.text {
  position: absolute;
  top: 278px;
  left: 46px;
  font-size: 32px;
  color:red;
  font-style: bold;
}
</style>
{% endblock %}

{% block extra_script %}
{% endblock %}

miningtaxes/templates/miningtaxes/index.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">text</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            {{ text }}
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

miningtaxes/templates/miningtaxes/launcher.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}

    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
            <h3 class="panel-title">{% translate 'Characters' %}</h3>
        </div>
        <div class="panel-body">
            <!-- Characters -->
            <div class="character-cards">
                <ul class="cards_container">
                    <!-- Add New Character -->
                    <li class="cards_item">
                        <div class="card">
                            <div class="card-header">{% translate 'Register Character' %}</div>

                            <div class="card-body card__content">
                                <a href="{% url 'miningtaxes:add_character' %}">
                                    <img src="{{ 1|character_portrait_url:256 }}" alt="Add character">
                                </a>
                            </div>

                            <div class="card-footer">
                                <a class="btn btn-primary btn-sm" href="{% url 'miningtaxes:add_character' %}">{% translate 'Register' %}</a>
                            </div>
                        </div>
                    </li>

                    {% if has_registered_characters %}
                        <!-- Registered Characters -->
                        {% for auth_character in auth_characters|dictsort:"character_name" %}
                            <li class="cards_item">
                                <div class="card">
                                    <div class="card-header">
                                        {{ auth_character.character_name }}
                                        {% if auth_character.character_id == main_character_id %}
                                            &nbsp;<i class="fas fa-crown" title="Main character"></i>
                                        {% endif %}
                                        {% if auth_character.character.is_shared %}
                                            &nbsp;<i class="far fa-eye" title="Currently shared with recruiters"></i>
                                        {% endif %}
                                    </div>

                                    <div class="card-body card__content">
                                        <p>
                                            <a href="{% url 'miningtaxes:character_viewer' auth_character.character.pk %}">
                                                <span class="aa-miningtaxes-launcher-character-image">
                                                    <img src="{{ auth_character.character_id|character_portrait_url:256 }}" alt="{{ auth_character.character_name }}">

                                                    {% if auth_character.alliance_id %}
                                                        <span class="aa-miningtaxes-alliance-logo">
                                                            <img class="" src="{{ auth_character.alliance_id|alliance_logo_url:64 }}" title="{{ auth_character.alliance_name }}">
                                                        </span>
                                                    {% endif %}

                                                    <span class="aa-miningtaxes-corporation-logo">
                                                        <img class="" src="{{ auth_character.corporation_id|corporation_logo_url:64 }}" title="{{ auth_character.corporation_name }}">
                                                    </span>
                                                </span>
                                            </a>
                                        </p>

                                        <div class="text-center">
                                            <br>
                                            {% if auth_character.character.wallet_balance %}
                                                {{ auth_character.character.wallet_balance.total|intword|default_if_none:"-" }} ISK<br>
                                            {% else %}
                                                <span class="text-muted">{% translate "(no data yet)" %}</span>
                                            {% endif %}

                                        </div>
                                    </div>

                                    <div class="card-footer">
                                        <a class="btn btn-success btn-sm" href="{% url 'miningtaxes:character_viewer' auth_character.character.pk %}"
                                            role="button" title="{% translate 'View this character.' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                        </a>

                                        <a class="btn btn-danger btn-sm" href="{% url 'miningtaxes:remove_character' auth_character.character.pk %}"
                                            role="button" title="{% translate 'Remove this character.' %}"
                                            onclick="return confirm('Are you sure you want to REMOVE this character?')">
                                            <i class="far fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>

            {% if unregistered_chars|length > 0 %}
                <p class="text-warning">
                    <strong>
                    <i class="fas fa-exclamation-triangle"></i>
                    {% translate 'Unregistered character(s):' %}&nbsp;&nbsp;</strong>
                    {{ unregistered_chars|join:", " }}
                </p>
            {% endif %}

        </div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'miningtaxes/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/miningtaxes.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
{% endblock %}

miningtaxes/templates/miningtaxes/ore_prices.html
{% extends 'miningtaxes/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}
{% load evelinks %}

{% block details %}
    <div class="panel panel-default">
        <div class="panel-heading" style="display:flex;">
		<h3 class="panel-title">Ore prices for 1000 units per ore</h3>
        </div>
        <div class="panel-body">

    <div class="table-responsive">
        <table class="table table-striped table-width-fix" id="ore_prices">
            <thead>
                <tr>
                    <th>{% translate 'Ore Group' %}</th>
                    <th>{% translate 'Ore' %}</th>
                    <th>{% translate 'Raw' %}</th>
                    <th>{% translate 'Refined' %}</th>
                    <th>{% translate 'Tax Rate' %}</th>
                    <th>{% translate 'Taxes' %}</th>
                    <th>{% translate 'After Taxes' %}</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
	</div>
    </div>

{% endblock details %}

{% block extra_javascript %}
{% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'miningtaxes/css/global.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/miningtaxes.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'miningtaxes/css/launcher.css' %}" type="text/css">
{% endblock %}

{% block extra_script %}
$(document).ready(function () {
        $('#ore_prices').DataTable({
            ajax: {
                url: "{% url 'miningtaxes:ore_prices_json' %}",
                dataSrc: 'data',
                cache: false
            },
            columns: [
                { data: 'group' },
                { data: 'name' },
                {
                    data: 'raw',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                {
                    data: 'refined',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                { data: 'tax_rate', },
                {
                    data: 'tax',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
                {
                    data: 'remaining',
                    render: $.fn.dataTable.render.number(',', '.', 2)
                },
            ],
            order: [[6, "desc"]],
	    pageLength: 50
        });
});
{% endblock %}